name: notes
channels:
 - conda-forge
dependencies:
 - astropy
 - astroML
 - emcee
 - ipython
 - jupyter
 - matplotlib
 - numba
 - numpy
 - pandas
 - python
 - scipy
 - scikit-learn
 - svgpathtools
 - sympy
 - pytorch
 - uncertainties
